package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/stax-ai/stax-cli/internal/deploy"
)

var (
	legacyInitPath        string
	legacyInitEnvironment string
	legacyInitForce       bool
)

func init() {
	legacyInitCmd := &cobra.Command{
		Use:   "legacy-init",
		Short: "Initialize deployment config.yaml for legacy cloud run functions",
		Long: `Initialize a deployment config.yaml file for legacy cloud run functions based on the repository name.

The command automatically determines the product (ta or cx) based on the repository name:
  - Repositories starting with "cx-" are configured as product: cx
  - Repositories starting with "stax-module" are configured as product: ta

The config.yaml will be created with appropriate defaults based on the repository name.`,
		Example: `  stax legacy-init
  stax legacy-init --path ./my-repo --environment prd
  stax legacy-init --force`,
		Args: cobra.NoArgs,
		RunE: runLegacyInit,
	}
	legacyInitCmd.Flags().StringVar(&legacyInitPath, "path", "", "directory to initialize (default: current directory)")
	legacyInitCmd.Flags().StringVar(&legacyInitEnvironment, "environment", "stg", "environment: prd or stg (default: stg)")
	legacyInitCmd.Flags().BoolVar(&legacyInitForce, "force", false, "overwrite existing config.yaml")
	rootCmd.AddCommand(legacyInitCmd)
}

func runLegacyInit(cmd *cobra.Command, args []string) error {
	projectRoot := legacyInitPath
	if projectRoot == "" {
		projectRoot = "."
	}
	absRoot, err := filepath.Abs(projectRoot)
	if err != nil {
		return fmt.Errorf("resolve project path: %w", err)
	}

	// Get repository name from directory
	repoName := filepath.Base(absRoot)

	// Determine product based on repo name
	var product string
	if strings.HasPrefix(repoName, "cx-") {
		product = "cx"
	} else if strings.HasPrefix(repoName, "stax-module") {
		product = "ta"
	} else {
		return fmt.Errorf("repository name must start with 'cx-' or 'stax-module' to determine product, got: %s", repoName)
	}

	// Validate environment
	if legacyInitEnvironment != "prd" && legacyInitEnvironment != "stg" {
		return fmt.Errorf("environment must be either 'prd' or 'stg', got: %s", legacyInitEnvironment)
	}

	// Service name is the repo name
	serviceName := repoName

	// Generate pub/sub topic name (typically matches service name or has a pattern)
	pubSubTopic := serviceName

	// Check if config.yaml already exists
	configPath := filepath.Join(absRoot, "config.yaml")
	if _, err := os.Stat(configPath); err == nil && !legacyInitForce {
		return fmt.Errorf("config.yaml already exists at %s (use --force to overwrite)", configPath)
	}

	// Create config
	cfg := &deploy.Config{
		ServiceName:   serviceName,
		PubSubTopic:   pubSubTopic,
		Product:       product,
		Environment:   legacyInitEnvironment,
		ImageRegistry: "", // User will need to set this
		ImageName:     serviceName,
		ImageTag:       "latest",
	}

	// Generate YAML
	configYAML := generateLegacyConfigYAML(cfg)

	// Write config.yaml
	if err := os.WriteFile(configPath, []byte(configYAML), 0644); err != nil {
		return fmt.Errorf("write config.yaml: %w", err)
	}

	cmd.Printf("Initialized deployment config.yaml at %s\n", configPath)
	cmd.Printf("  Service: %s\n", serviceName)
	cmd.Printf("  Product: %s\n", product)
	cmd.Printf("  Environment: %s\n", legacyInitEnvironment)
	cmd.Printf("  Namespace: %s\n", cfg.GetNamespace())
	cmd.Printf("\nPlease update config.yaml with:\n")
	cmd.Printf("  - image_registry: your container registry URL\n")
	cmd.Printf("  - pubsub_topic: your pub/sub topic name (if different from service name)\n")

	return nil
}

func generateLegacyConfigYAML(cfg *deploy.Config) string {
	var b strings.Builder
	b.WriteString("# Deployment configuration for legacy cloud run function\n")
	b.WriteString("# Generated by: stax legacy-init\n\n")
	b.WriteString(fmt.Sprintf("service_name: %s\n", cfg.ServiceName))
	b.WriteString(fmt.Sprintf("pubsub_topic: %s\n", cfg.PubSubTopic))
	b.WriteString(fmt.Sprintf("product: %s\n", cfg.Product))
	b.WriteString(fmt.Sprintf("environment: %s\n", cfg.Environment))
	if cfg.ImageRegistry != "" {
		b.WriteString(fmt.Sprintf("image_registry: %s\n", cfg.ImageRegistry))
	} else {
		b.WriteString("# image_registry: # Set your container registry URL (e.g., gcr.io/my-project)\n")
	}
	if cfg.ImageName != "" && cfg.ImageName != cfg.ServiceName {
		b.WriteString(fmt.Sprintf("image_name: %s\n", cfg.ImageName))
	}
	if cfg.ImageTag != "" && cfg.ImageTag != "latest" {
		b.WriteString(fmt.Sprintf("image_tag: %s\n", cfg.ImageTag))
	}
	if cfg.Namespace != "" {
		b.WriteString(fmt.Sprintf("namespace: %s\n", cfg.Namespace))
	}
	return b.String()
}
